name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false
      - name: Config Cmake and Compile
        run: |
          cmake -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build
      - name: Do Test
        run: |
          cd ${{github.workspace}}/build
          ./SortAlgorithm
